apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ2YWxheHkwNTU1Lmpmcm9nLmlvIjogewoJCQkiYXV0aCI6ICJkbUZzWVhoNU1EVTFOVHBTYjI1cGRITmhhVUF4TWpNPSIKCQl9Cgl9Cn0= 
type: kubernetes.io/dockerconfigjson